CREATE DATABASE IF NOT EXISTS web_03mc;
USE web_03mc;

CREATE TABLE IF NOT EXISTS produtos_seu_nome (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  descricao TEXT,
  preco DECIMAL(10, 2) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
